#!/usr/bin/env ruby
 
unless ARGV[0]
  puts 'Usage: newpost "the post title" [draft post]'
  exit(-1)
end
 
date_prefix = Time.now.strftime("%Y-%m-%d")
postname = ARGV[0].strip.downcase.gsub(/ /, '-')
post_type = ARGV[1] == "-d" ? '_drafts' : '_posts'
post = "/Users/lake/Projects/lakedenman.com/#{post_type}/#{date_prefix}-#{postname}.markdown"
 
header = <<-END
---
layout: post
title: "#{ARGV[0]}"
---
 
# {{ page.title }}
 
END
 
File.open(post, 'w') do |f|
  f << header
end
 
system("mate", "-a", post)