#!/usr/bin/env ruby

require 'optparse'

options = {}

optparse = OptionParser.new do |opts|
  opts.banner = "Usage: script/newpost [options] title"
  
  options[:draft] = false
  opts.on('-d', '--draft', 'Create the post inside of the _drafts folder') do
    options[:draft] = true
  end
  
  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end
end 

optparse.parse!

date = Time.now.strftime("%Y-%m-%d")
postname = ARGV[0].strip.downcase.gsub(/ /, '-') if ARGV[0]
area = options[:draft] ? '_drafts' : '_posts'
post = File.join(File.dirname('.'), "#{area}", "#{date}-#{postname}.markdown")
 
header = <<-END
---
layout: post
title: #{ARGV[0]}
excerpt: #{ARGV[0]}...
---
 
END
 
File.open(post, 'w') do |f|
  f << header
end
 
system("mate", "-a", post)